import { Button } from '../components/ui/Button.js';
import { Badge } from '../components/ui/Badge.js';
import { EmptyState } from '../components/ui/EmptyState.js';
import { StatCard, StatusBadge, DataTable } from '../components/ui/AdminPrimitives.js';
import { adminIcon } from '../components/layout/AdminLayout.js';
import { escapeHtml as e } from '../utils/html.js';
import { filterUsers, money, dateTime, pageItems, revenue } from '../utils/admin.js';

export const heading = (title, description, action = '') => `<div class="admin-page-heading"><div><p class="eyebrow mb-3">HAPPYPROGRAMMING ADMIN</p><h1>${e(title)}</h1><p>${e(description)}</p></div>${action}</div>`;
const panel = (title, description, content, action = '') => `<section class="admin-panel"><div class="admin-panel-heading"><div><h2>${e(title)}</h2>${description ? `<p>${e(description)}</p>` : ''}</div>${action}</div>${content}</section>`;
const empty = (title = 'No results found', description = 'Try another search or clear the filters.') => EmptyState({ id: 'admin-empty', title, description, buttonText: '', hidden: false });
const person = user => `<div class="admin-person"><span class="admin-avatar">${e(user.name.split(/\s+/).map(p => p[0]).slice(0, 2).join(''))}</span><div><strong>${e(user.name)}</strong><small>${e(user.email)}</small></div></div>`;
const select = (id, label, values, current = '', all = 'All') => `<label class="admin-field" for="${id}">${e(label)}<select id="${id}" name="${id}">${all ? `<option value="">${e(all)}</option>` : ''}${values.map(v => `<option value="${e(v)}" ${v === current ? 'selected' : ''}>${e(v.charAt(0) + v.slice(1).toLowerCase())}</option>`).join('')}</select></label>`;
function pagination(result) {
  return `<div class="admin-pagination"><p>${result.total ? (result.page - 1) * 8 + 1 : 0}–${Math.min(result.page * 8, result.total)} of ${result.total} results</p><div>${Button({ id: 'admin-prev', label: 'Previous', variant: 'outline', size: 'sm', disabled: result.page === 1 })}<span class="self-center px-2">${result.page} / ${result.pages}</span>${Button({ id: 'admin-next', label: 'Next', variant: 'outline', size: 'sm', disabled: result.page === result.pages })}</div></div>`;
}
function stats(data, report) {
  return `<div class="admin-stats">${StatCard({ label: 'Community accounts', value: data.users.length, note: `${data.users.filter(u => u.status === 'ACTIVE').length} active accounts`, icon: adminIcon('users') })}${StatCard({ label: 'Active mentors', value: data.users.filter(u => u.role === 'MENTOR' && u.status === 'ACTIVE').length, note: 'Accounts with active status', icon: adminIcon('staff') })}${StatCard({ label: 'Gross payments', value: money(report.gross), note: 'Verified VNPay · all time', icon: adminIcon('revenue') })}${StatCard({ label: 'Platform commission', value: money(report.commission), note: 'Historical commission rates · all time', icon: adminIcon('settings') })}</div>`;
}
function chart(payments) {
  const now = new Date();
  const months = Array.from({ length: 6 }, (_, index) => {
    const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 5 + index, 1));
    const key = date.toISOString().slice(0, 7);
    return { label: date.toLocaleDateString('en-US', { month: 'short', timeZone: 'UTC' }), total: payments.filter(p => p.paidAt.startsWith(key)).reduce((s, p) => s + Number(p.amount), 0) };
  });
  const maximum = Math.max(...months.map(m => m.total), 1);
  return `<div class="admin-chart" role="img" aria-label="${e(months.map(m => `${m.label}: ${money(m.total)}`).join('; '))}">${months.map(m => `<div class="admin-chart-column"><div class="admin-chart-bar" style="height:${Math.round(m.total / maximum * 150)}px" title="${e(money(m.total))}"></div><span>${e(m.label)}</span></div>`).join('')}</div>`;
}
export function OverviewView(data, session) {
  const report = revenue(data.payments);
  return heading(`Welcome back, ${session.name.split(' ')[0]}.`, 'A little oversight, a thriving community. Here is your platform at a glance.', `<a class="btn btn-primary" href="#/admin/revenue">View revenue report ${adminIcon('revenue')}</a>`) + stats(data, report) +
    `<div class="admin-grid">${panel('Revenue overview', 'Verified gross payments · last 6 calendar months · VND', `<div class="admin-panel-body"><p class="text-[28px] font-semibold">${money(report.payments.filter(p => p.paidAt.slice(0, 7) === new Date().toISOString().slice(0, 7)).reduce((s, p) => s + Number(p.amount), 0))}</p><p class="text-[11px] text-muted mt-1">This month · UTC</p>${chart(report.payments)}</div>`)}${panel('Recent activity', 'A clear record of every administrative change', `<div class="admin-panel-body admin-activity">${data.audit.slice(0, 4).map(a => `<div class="admin-activity-item"><span class="admin-avatar">${adminIcon('audit')}</span><div><p class="font-semibold">${e(a.action.replaceAll('_', ' ').toLowerCase())}</p><p>${e(a.actor)} · ${e(a.target)}</p><small>${e(dateTime(a.createdAt))}</small></div></div>`).join('') || empty('No activity yet', 'Administrative changes will appear here.')}</div>`, '<a class="text-brand text-[11px] font-semibold" href="#/admin/audit">View all</a>')}</div>` +
    panel('Recently joined', 'The newest members of your community', DataTable({ caption: 'Recently joined accounts', headings: ['Member', 'Role', 'Status', 'Joined'], rows: data.users.slice(0, 5).map(u => [person(u), Badge({ text: e(u.role.toLowerCase()) }), StatusBadge(u.status), e(dateTime(u.createdAt))]), empty: empty('No accounts yet', 'Accounts will appear after registration.') }), '<a class="text-brand text-[11px] font-semibold" href="#/admin/users">Manage users →</a>');
}
export function UsersView(data, state, staff = false) {
  const result = pageItems(filterUsers(data.users, { ...state, role: staff ? 'STAFF' : state.role }), state.page);
  state.page = result.page;
  return heading(staff ? 'Staff & permissions' : 'User management', staff ? 'Give your operations team the right access to support the community.' : 'Find members, review account access, and keep your community healthy.') + panel(staff ? 'Staff directory' : 'All users', `${result.total} ${staff ? 'staff accounts' : 'matching accounts'}`, `
    <form id="admin-filters" class="admin-toolbar"><label class="admin-field admin-search" for="admin-query">Search ${staff ? 'staff' : 'users'}<input id="admin-query" name="query" type="search" value="${e(state.query)}" placeholder="Search by name or email" maxlength="100"></label>${staff ? '' : select('role', 'Role', ['ADMIN', 'STAFF', 'MENTOR', 'MENTEE'], state.role, 'All roles')}${select('status', 'Status', ['ACTIVE', 'INACTIVE', 'LOCKED'], state.status, 'All statuses')}${Button({ label: 'Search', type: 'submit', variant: 'secondary' })}${Button({ id: 'admin-clear', label: 'Clear', variant: 'ghost' })}</form>
    ${DataTable({ caption: staff ? 'Staff accounts and permissions' : 'Community accounts', headings: ['Member', staff ? 'Permissions' : 'Role', 'Status', 'Joined (UTC)', 'Action'], rows: result.items.map(u => [person(u), staff ? `${u.permissions.length} of 4 assigned` : Badge({ text: e(u.role.toLowerCase()) }), StatusBadge(u.status), e(dateTime(u.createdAt).replace(' UTC', '')), `<button class="btn btn-outline btn-sm" data-${staff ? 'permissions' : 'user'}="${u.id}" aria-label="${staff ? 'Edit permissions for' : 'View account of'} ${e(u.name)}">${staff ? 'Edit permissions' : 'View account'}</button>`]), empty: empty() })}${pagination(result)}`);
}
export function RevenueView(data, state) {
  const report = revenue(data.payments, state.from, state.to);
  const result = pageItems(report.payments, state.page); state.page = result.page;
  return heading('Revenue reports', 'Verified payments and the platform commission earned on each transaction.') +
    `<div class="admin-stats">${StatCard({ label: 'Gross payments', value: money(report.gross), note: 'Selected period · VND' })}${StatCard({ label: 'Platform commission', value: money(report.commission), note: 'Original transaction rates' })}${StatCard({ label: 'Mentor share', value: money(report.gross - report.commission), note: 'Before refunds and settlement' })}${StatCard({ label: 'Verified transactions', value: report.payments.length, note: 'Successful VNPay payments only' })}</div>` +
    panel('Payment ledger', 'Amounts are gross of refunds. This report does not represent available escrow or payout balances.', `<form id="admin-dates" class="admin-toolbar"><label class="admin-field" for="from">From (UTC)<input type="date" id="from" name="from" value="${e(state.from)}"></label><label class="admin-field" for="to">To (UTC)<input type="date" id="to" name="to" value="${e(state.to)}"></label>${Button({ label: 'Apply dates', variant: 'secondary', type: 'submit' })}${Button({ label: 'All time', variant: 'ghost', id: 'admin-clear' })}${Button({ label: 'Export CSV', variant: 'outline', id: 'admin-export', disabled: !report.payments.length })}</form>${DataTable({ caption: 'Verified VNPay payments', headings: ['Reference', 'Paid at (UTC)', 'Gross amount', 'Commission', 'Rate', 'Status'], rows: result.items.map(p => [e(p.reference), e(dateTime(p.paidAt).replace(' UTC', '')), money(p.amount), money(Number(p.amount) * Number(p.commissionRate) / 100), `${e(p.commissionRate)}%`, StatusBadge(p.status)]), empty: empty('No verified payments', 'No successful VNPay transactions match this period.') })}${pagination(result)}`);
}
export function SettingsView(data) {
  return heading('System settings', 'Manage platform contact details and the commission for new payments.') + panel('Platform configuration', 'Changes require a reason and are recorded in the audit log.', `<form id="admin-settings" class="admin-panel-body admin-form"><div class="admin-form-grid"><label class="admin-field" for="commissionRate">Platform commission (%)<input id="commissionRate" name="commissionRate" type="number" min="0" max="100" step="0.01" value="${e(data.settings.commissionRate)}" required><span class="text-muted font-normal">Only applies to future payments. Existing rates stay unchanged.</span></label><label class="admin-field" for="supportEmail">Support email<input id="supportEmail" name="supportEmail" type="email" maxlength="254" value="${e(data.settings.supportEmail)}" placeholder="support@example.com"><span class="text-muted font-normal">Leave blank if a support address has not been configured.</span></label></div><label class="admin-field" for="settings-reason">Reason for change<textarea id="settings-reason" name="reason" rows="3" required maxlength="1000" placeholder="Explain why this update is needed"></textarea></label><div class="admin-actions">${Button({ id: 'admin-settings-reset', label: 'Discard changes', variant: 'outline' })}${Button({ label: 'Review changes', type: 'submit' })}</div></form>`);
}
export function AuditView(data, state) {
  const q = state.query.toLowerCase().trim();
  const records = data.audit.filter(a => `${a.actor} ${a.action} ${a.target} ${a.reason || ''}`.toLowerCase().includes(q));
  const result = pageItems(records, state.page); state.page = result.page;
  return heading('Audit logs', 'An immutable history of account, staff authorization, and configuration changes.', Badge({ text: 'Read-only history' })) + panel('Activity history', 'All timestamps are shown in UTC. Audit records cannot be edited or deleted.', `<form id="admin-filters" class="admin-toolbar"><label class="admin-field admin-search" for="admin-query">Search activity<input id="admin-query" name="query" type="search" value="${e(state.query)}" placeholder="Search actor, action, target or reason" maxlength="100"></label>${Button({ label: 'Search', type: 'submit', variant: 'secondary' })}${Button({ id: 'admin-clear', label: 'Clear', variant: 'ghost' })}</form>${DataTable({ caption: 'Immutable audit records', headings: ['Timestamp (UTC)', 'Actor', 'Action / target', 'Reason', 'IP address'], rows: result.items.map(a => [e(dateTime(a.createdAt).replace(' UTC', '')), `${e(a.actor)}${a.actorId ? `<small class="block text-muted mt-1">ID ${e(a.actorId)}</small>` : ''}`, `<span class="font-semibold">${e(a.action)}</span><small class="block text-muted mt-1">${e(a.target)}</small>`, `<span class="block whitespace-normal min-w-40 max-w-xs">${e(a.reason || 'No reason recorded')}</span>`, e(a.ipAddress || 'Not recorded')]), empty: empty('No activity found', 'Try another search. New administrative changes appear here.') })}${pagination(result)}`);
}
