package com.happyprogramming.role.admin;

import com.happyprogramming.role.admin.AdminDtos;
import com.happyprogramming.role.admin.AdminRepository;
import com.happyprogramming.role.admin.AdminService;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Bean;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import static org.junit.jupiter.api.Assertions.*;

@JdbcTest(properties={"spring.flyway.enabled=false"})
@Import({AdminRepository.class, AdminService.class, AdminRepositoryTest.JsonConfig.class})
@Transactional(propagation=Propagation.NOT_SUPPORTED)
public class AdminRepositoryTest {
    @TestConfiguration static class JsonConfig { @Bean ObjectMapper mapper() { return new ObjectMapper().findAndRegisterModules(); } }
    @Autowired JdbcTemplate jdbc;
    @Autowired AdminRepository repository;
    @Autowired AdminService service;
    @BeforeEach void setup() {
        jdbc.execute("SET MODE MSSQLServer");
        jdbc.execute("CREATE SCHEMA IF NOT EXISTS dbo");
        jdbc.execute("CREATE ALIAS IF NOT EXISTS SYSUTCDATETIME FOR 'com.happyprogramming.role.admin.AdminRepositoryTest.utcNow'");
        jdbc.execute("DROP TABLE IF EXISTS dbo.payments, dbo.audit_logs, dbo.user_permissions, dbo.users, dbo.system_configs");
        jdbc.execute("CREATE TABLE dbo.users(id BIGINT PRIMARY KEY, full_name VARCHAR(150), email VARCHAR(254), role_code VARCHAR(20), status VARCHAR(20), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP)");
        jdbc.execute("CREATE TABLE dbo.user_permissions(user_id BIGINT, permission_code VARCHAR(80), assigned_by BIGINT)");
        jdbc.execute("CREATE TABLE dbo.audit_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_id BIGINT, action VARCHAR(100), entity_type VARCHAR(100), entity_id VARCHAR(150), old_values VARCHAR(4000), new_values VARCHAR(4000), reason VARCHAR(1000) CHECK(reason <> 'reject-audit'), ip_address VARCHAR(45), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE dbo.payments(id BIGINT, merchant_reference VARCHAR(100), amount DECIMAL(18,2), commission_rate_snapshot DECIMAL(5,2), status VARCHAR(20), gateway VARCHAR(30), gateway_transaction_id VARCHAR(100), paid_at TIMESTAMP, currency VARCHAR(3))");
        jdbc.execute("CREATE TABLE dbo.system_configs(config_key VARCHAR(150) PRIMARY KEY, config_value VARCHAR(4000), updated_by BIGINT, updated_at TIMESTAMP)");
        jdbc.update("INSERT INTO dbo.users(id,full_name,email,role_code,status) VALUES(1,'Admin','admin@example.com','ADMIN','ACTIVE'),(2,'Member','member@example.com','MENTEE','ACTIVE')");
        jdbc.update("INSERT INTO dbo.system_configs(config_key,config_value) VALUES('finance.commission_rate','{\"value\":15.00}'),('platform.support_email','{\"value\":null}')");
    }
    public static java.sql.Timestamp utcNow() { return java.sql.Timestamp.valueOf(java.time.LocalDateTime.now(java.time.ZoneOffset.UTC)); }
    @Test void revenueQueryOnlyReturnsVerifiedVndVnpayPayments() {
        jdbc.update("INSERT INTO dbo.payments VALUES(1,'good',100000,12,'SUCCEEDED','VNPAY','verified',CURRENT_TIMESTAMP,'VND'),(2,'failed',200000,15,'FAILED','VNPAY','failed',CURRENT_TIMESTAMP,'VND'),(3,'unverified',300000,15,'SUCCEEDED','VNPAY',NULL,CURRENT_TIMESTAMP,'VND'),(4,'other',400000,15,'SUCCEEDED','OTHER','verified',CURRENT_TIMESTAMP,'VND'),(5,'currency',500000,15,'SUCCEEDED','VNPAY','verified',CURRENT_TIMESTAMP,'USD')");
        var result = repository.payments(); assertEquals(1, result.size()); assertEquals("good", result.get(0).reference()); assertEquals(new BigDecimal("12.00"), result.get(0).commissionRate());
    }
    @Test void accountUpdateRollsBackWhenAuditInsertFails() {
        assertThrows(org.springframework.dao.DataIntegrityViolationException.class, () -> service.status(2, new AdminDtos.StatusChange("LOCKED", "reject-audit"), new AdminDtos.Session(1,"Admin","admin@example.com"),"127.0.0.1"));
        assertEquals("ACTIVE", jdbc.queryForObject("SELECT status FROM dbo.users WHERE id=2", String.class));
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM dbo.audit_logs", Integer.class));
    }
    @Test void statusAndAuditCommitAndReadBack() {
        service.status(2, new AdminDtos.StatusChange("LOCKED", "Review account"), new AdminDtos.Session(1,"Admin","admin@example.com"),"127.0.0.1");
        assertEquals("LOCKED", repository.accounts().stream().filter(u -> u.id()==2).findFirst().orElseThrow().status());
        assertEquals("Review account", repository.audit().get(0).reason()); assertEquals(1L, repository.audit().get(0).actorId());
    }
    @Test void settingsMaintainJsonShapeAndAuditHistory() {
        service.settings(new AdminDtos.SettingsChange(new BigDecimal("20.00"),"help@example.com","New rate"), new AdminDtos.Session(1,"Admin","admin@example.com"),"127.0.0.1");
        assertEquals(0, new BigDecimal("20.00").compareTo(repository.settings().commissionRate()));
        assertEquals("help@example.com", repository.settings().supportEmail()); assertEquals("SETTINGS_CHANGED", repository.audit().get(0).action());
    }
}
